Repository josoavj/ai.assistant, pull requests merged in 2024-07, with the labels that each got.

#1 UI patch1
  README.md
  lib/api/api.dart
  lib/main.dart
  lib/screens/intro.dart
Labels: good first issue

#2 style: Code improvement
  lib/api/api.dart
  lib/main.dart
Labels: enhancement

#3 UI patch1
  .vscode/launch.json
  lib/api/api.dart
  lib/pages/about.dart
  lib/screens/intro.dart
Labels: features, minor update

#4 UI - Improvement
  assets/images/todoroki.png
  lib/api/api.dart
  lib/screens/intro.dart
  pubspec.yaml
Labels: minor update, dependencies

#5 UI patch1
  lib/api/api.dart
  lib/pages/about.dart
  lib/pages/settings.dart
Labels: minor update

#6 docs: Updating readme
  README.md
Labels: documentation

#7 Firebase Authentification & Profile page
  .vscode/settings.json
  android/app/build.gradle
  android/app/google-services.json
  android/app/google-services.json.old
  android/build.gradle
  android/settings.gradle
  firebase.json
  lib/api/api.dart
  lib/firebase_options.dart
  lib/pages/profile.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: features, dependencies

#8 Security policy initialisation
  SECURITY.md
Labels: documentation

#9 deps: Adding font_awesome to dependencies
  pubspec.lock
  pubspec.yaml
Labels: dependencies

#11 UI improvement & New features on the About page
  lib/pages/about.dart
  lib/pages/profile.dart
  lib/pages/settings.dart
Labels: features, minor update

#12 UI Improvement
  lib/pages/about.dart
  lib/pages/profile.dart
Labels: minor update

#13 build: Google service package update
  android/app/google-services.json
Labels: minor update

#14 UI patch1
  .vscode/settings.json
  pubspec.lock
Labels: dependencies

#15 Refactoring the project structure
  lib/api/api.dart
  lib/api/api_call.dart
  lib/others/app_theme.dart
  lib/others/screenswidget.dart
  lib/pages/profile.dart
  lib/screens/chatscreen.dart
  lib/screens/chatwidget.dart
  lib/screens/intro.dart
Labels: features

#16 UI patch1
  README.md
  lib/pages/about.dart
Labels: dependencies
